spring:
  application:
    name: order
  jpa:
    open-in-view: false
    show-sql: true
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  kafka:
    producer:
      bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
      properties:
        spring.json.add.type.headers: "false"

order:
  order-created-kafka-topic: "order-created"
  order-updated-kafka-topic: "order-updated"


logging:
  level:
    org.springframework.modulith: DEBUG
    org.springframework.orm.jpa: DEBUG
